from typing import Optional, List, Dict
import os
from openai import AsyncOpenAI

class SimpleRAGChatbot:
    """Simplified RAG chatbot without Qdrant dependency"""
    
    def __init__(self):
        print("Initializing Simple RAG Chatbot (without Qdrant)...")
        
        openai_key = os.getenv("OPENAI_API_KEY")
        if not openai_key:
            raise ValueError("OPENAI_API_KEY not found in environment")
            
        self.openai_client = AsyncOpenAI(api_key=openai_key)
        print("✓ Simple RAG Chatbot initialized successfully!")
    
    async def get_response(
        self,
        message: str,
        selected_text: Optional[str] = None,
        chapter: Optional[str] = None,
        user_profile: Optional[dict] = None
    ) -> dict:
        """Generate response using OpenAI without RAG"""
        
        # Build system prompt
        system_prompt = """You are an expert AI assistant for the Physical AI & Humanoid Robotics course.
        You help students learn about ROS 2, Gazebo, Unity, NVIDIA Isaac, and Vision-Language-Action systems.
        Be helpful, accurate, and concise. Provide practical examples when relevant."""
        
        if user_profile:
            system_prompt += f"""
            
            User Background:
            - Software: {user_profile.get('software_background', 'Not specified')}
            - Hardware: {user_profile.get('hardware_background', 'Not specified')}
            - Programming: {user_profile.get('programming_experience', 'Not specified')}
            - Robotics: {user_profile.get('robotics_experience', 'Not specified')}
            
            Tailor your response to their experience level.
            """
        
        # Add context if provided
        context_message = message
        if selected_text:
            context_message = f"Context: {selected_text}\n\nQuestion: {message}"
        elif chapter:
            context_message = f"[From {chapter}]\n\nQuestion: {message}"
        
        # Generate response
        try:
            response = await self.openai_client.chat.completions.create(
                model="gpt-4-turbo-preview",
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": context_message}
                ],
                temperature=0.7,
                max_tokens=1000
            )
            
            return {
                "response": response.choices[0].message.content,
                "sources": [{"type": "ai_generated", "note": "Response generated by GPT-4"}]
            }
        except Exception as e:
            print(f"Error generating response: {e}")
            return {
                "response": f"I'm having trouble processing your request. Error: {str(e)}",
                "sources": []
            }
    
    async def personalize_content(self, content: str, user_background: dict) -> str:
        """Personalize content based on user background"""
        
        prompt = f"""Adapt the following technical content for a learner with this background:
        
        Software Background: {user_background.get('software_background', 'Not specified')}
        Hardware Background: {user_background.get('hardware_background', 'Not specified')}
        Programming Experience: {user_background.get('programming_experience', 'Not specified')}
        Robotics Experience: {user_background.get('robotics_experience', 'Not specified')}
        
        Original Content:
        {content}
        
        Provide a personalized version that:
        1. Adjusts technical depth to their level
        2. Adds relevant examples from their background
        3. Highlights connections to their experience
        4. Suggests prerequisites if needed
        """
        
        try:
            response = await self.openai_client.chat.completions.create(
                model="gpt-4-turbo-preview",
                messages=[{"role": "user", "content": prompt}],
                temperature=0.7,
                max_tokens=2000
            )
            return response.choices[0].message.content
        except Exception as e:
            print(f"Error personalizing content: {e}")
            return content
    
    async def translate_content(self, content: str, target_language: str = "ur") -> str:
        """Translate content to target language (Urdu)"""
        
        language_names = {
            "ur": "Urdu (اردو)",
            "en": "English"
        }
        
        prompt = f"""Translate the following technical content to {language_names.get(target_language, target_language)}.
        
        Maintain:
        - Technical terms (keep English terms in parentheses)
        - Code snippets (don't translate)
        - Formatting and structure
        - Accuracy of technical concepts
        
        Content:
        {content}
        """
        
        try:
            response = await self.openai_client.chat.completions.create(
                model="gpt-4-turbo-preview",
                messages=[{"role": "user", "content": prompt}],
                temperature=0.3,
                max_tokens=2000
            )
            return response.choices[0].message.content
        except Exception as e:
            print(f"Error translating content: {e}")
            return content
